project_id = "ftmdwfladqfrwxnejtpu"

[functions.get-services]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.get-orders]
verify_jwt = false

[functions.get-user-profile]
verify_jwt = false

[functions.smm-provider]
verify_jwt = false